### ISSUE TITLE
The solution does not work anymore?

### ISSUE THREAD

**Issue by tbarbette** [jonashackt/vagrant-github-actions#5]
Hi all,

I used macos-12 up to recently where VM now stays in gurumediation state. I tried to revert to 10.15 but the job is never picked up by a runner, I guess there's no macos10 runners anymore now.

I tried macos10 to 13 without success.

Does anyone has a solution ?

Thanks,

**Comment by michaelachrisco** [comment]
I would also like to know if something like this works or if anyone has found a workaround. I may have to hard switch over to docker/docker-compose (which is fine) but we have an existing Vagrant that I would like to test out in Actions.

**Comment by jonashackt** [comment]
Oh, that's not good to hear - I don't have the time right now, but does libvrt work as a workaround?! As described here for TravisCI https://github.com/jonashackt/vagrant-travisci-libvrt

**Comment by APN-Pucky** [comment]
Following https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/ I use linux (ubuntu-latest) + virtualbox(/qemu/libvirt) in my vagrant github action setup:
https://github.com/APN-Pucky/gentoo-prefix-tester/blob/1ecbecb7c14efa92b0899e37f32604eea764bdb7/actions/kvm/action.yml#L34-L54

**Comment by PeterJCLaw** [comment]
Looks like for VirtualBox + Vagrant on Ubuntu this now pretty simple -- just a case of installing the packages:
```
sudo apt-get install -y virtualbox vagrant
```
This depends on having added the vagrant repo though (see https://developer.hashicorp.com/vagrant/install#linux).

Aside from that I found I needed to set the target for a bridged network explicitly to prevent vagrant trying to use a TTY (which would fail).

**Comment by tbarbette** [comment]
Can you share a minimal CI file please?

**Comment by PeterJCLaw** [comment]
Minimal example:
```yml
name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        shell: bash
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update
          sudo apt-get install -y virtualbox vagrant

      - run: vagrant --version

      - run: vagrant up --provision
```

Untested in isolation, but cut down from the file in https://github.com/PeterJCLaw/srcomp-puppet/pull/34.
